<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="Bogus" Version="35.6.5" />
    <PackageVersion Include="Candoumbe.Pipelines" Version="3.1.0" />
    <PackageVersion Include="Candoumbe.MiscUtilities" Version="0.15.0" />
    <PackageVersion Include="coverlet.msbuild" Version="6.0.4" />
    <PackageVersion Include="FluentAssertions" Version="[7.2.2]" />
    <PackageVersion Include="FluentValidation" Version="11.12.0" />
    <PackageVersion Include="FsCheck.XUnit" Version="3.4.0" />
    <PackageVersion Include="Microsoft.Bcl.Memory" Version="10.0.4"/>
    <PackageVersion Include="Microsoft.Build" Version="18.9.6" />
    <PackageVersion Include="Microsoft.Build.Framework" Version="18.9.6" />
    <PackageVersion Include="Microsoft.Build.Tasks.Core" Version="18.9.6" />
    <PackageVersion Include="Microsoft.Build.Utilities.Core" Version="18.9.6" />
    <PackageVersion Include="Microsoft.Extensions.Primitives" Version="9.0.20" Condition="'$(TargetFramework)' == 'net8.0'"  />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="NodaTime.Bogus" Version="3.0.2" />
    <PackageVersion Include="NuGet.Packaging" Version="6.14.3" />
    <PackageVersion Include="Optional" Version="4.0.0" />
    <PackageVersion Include="Roslynator.Analyzers" Version="4.16.1" />
    <PackageVersion Include="System.Security.Cryptography.Xml" Version="10.0.11" />
    <PackageVersion Include="TngTech.ArchUnitNET.xUnitV3" Version="0.13.4"/>
    <PackageVersion Include="Stateless" Version="5.20.1" />
    <PackageVersion Include="Ultimately" Version="3.0.0" />
    <PackageVersion Include="xunit.categories" Version="2.0.8" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsTestProject)' == 'false'">
    <PackageVersion Include="DotNet.ReproducibleBuilds" Version="1.2.39" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' != 'netstandard1.3'">
    <PackageVersion Include="Ardalis.GuardClauses" Version="5.0.0" />
  </ItemGroup>
</Project>