#!/usr/bin/env bash

set -euo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
env_file="$script_dir/../.env"

force_engine=""

while [ $# -gt 0 ]; do
  case "$1" in
    --force-engine)
      force_engine="${2:-}"
      shift 2
      ;;
    --help|-h)
      echo "Usage: select-engine.sh [--force-engine podman|docker]"
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 2
      ;;
  esac
done

if [ -n "$force_engine" ]; then
  case "$force_engine" in
    podman|docker)
      engine="$force_engine"
      ;;
    *)
      echo "Invalid --force-engine value: $force_engine" >&2
      exit 2
      ;;
  esac
else
  if command -v podman >/dev/null 2>&1; then
    engine="podman"
  elif command -v docker >/dev/null 2>&1; then
    engine="docker"
  else
    echo "Neither podman nor docker was found in PATH." >&2
    exit 1
  fi
fi

docker_host=""

if [ "$engine" = "podman" ]; then
  uid="$(id -u)"
  if [ -S "/run/user/$uid/podman/podman.sock" ]; then
    docker_host="unix:///run/user/$uid/podman/podman.sock"
  elif [ -S "/run/podman/podman.sock" ]; then
    docker_host="unix:///run/podman/podman.sock"
  fi
fi

cat > "$env_file" <<EOF
# Generated by .devcontainer/scripts/select-engine.sh
CONTAINER_ENGINE=$engine
EOF

if [ -n "$docker_host" ]; then
  echo "DOCKER_HOST=$docker_host" >> "$env_file"
fi

echo "Selected container engine: $engine"
if [ -n "$docker_host" ]; then
  echo "DOCKER_HOST=$docker_host"
fi