param(
  [ValidateSet("podman", "docker")]
  [string]$ForceEngine
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$EnvFile = Join-Path $ScriptDir "..\.env"

function Test-CommandExists {
  param([string]$Name)
  return [bool](Get-Command $Name -ErrorAction SilentlyContinue)
}

if ($ForceEngine) {
  $engine = $ForceEngine
} elseif (Test-CommandExists "podman") {
  $engine = "podman"
} elseif (Test-CommandExists "docker") {
  $engine = "docker"
} else {
  Write-Error "Neither podman nor docker was found in PATH."
  exit 1
}

$dockerHost = ""

if ($engine -eq "podman") {
  if ($IsWindows) {
    $pipePath = "\\.\pipe\podman-machine-default"
    if (Test-Path $pipePath) {
      $dockerHost = "npipe:////./pipe/podman-machine-default"
    }
  } else {
    try {
      $uid = & id -u
    } catch {
      $uid = ""
    }

    if ($uid) {
      $userSock = "/run/user/$uid/podman/podman.sock"
      if (Test-Path $userSock) {
        $dockerHost = "unix://$userSock"
      }
    }

    if (-not $dockerHost) {
      $rootSock = "/run/podman/podman.sock"
      if (Test-Path $rootSock) {
        $dockerHost = "unix://$rootSock"
      }
    }
  }
}

@(
  "# Generated by .devcontainer/scripts/select-engine.ps1",
  "CONTAINER_ENGINE=$engine"
) | Set-Content -Path $EnvFile -Encoding UTF8

if ($dockerHost) {
  "DOCKER_HOST=$dockerHost" | Add-Content -Path $EnvFile -Encoding UTF8
}

Write-Host "Selected container engine: $engine"
if ($dockerHost) {
  Write-Host "DOCKER_HOST=$dockerHost"
}